# Custom Build Options
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = yes
COMMAND_ENABLE = no
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no
ENCODER_ENABLE = no
TAP_DANCE_ENABLE = no
RGB_MATRIX_ENABLE = yes
LTO_ENABLE = yes